kind: Deployment
apiVersion: apps/v1
metadata:
  name: kudos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kudos-quarkus-app
  template:
    metadata:
      labels:
        app: kudos-quarkus-app
    spec:
      containers:
        - name: kudos-app
          image: java-quarkus-image:latest
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
---
kind: Service
apiVersion: v1
metadata:
  name: kudos-app-svc
spec:
  ports:
    - name: http-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kudos-quarkus-app