greeting:
  message: "hello"

quarkus:
  http:
    host: 0.0.0.0
  profile: dev
  openshift:
    build-strategy: docker
    route:
      expose: true
    jvm-dockerfile: src/main/docker/Dockerfile.jvm
  kubernetes-client:
    trust-certs: true